{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "geopulse.fullname" . }}
  labels:
    {{- include "geopulse.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          {{- with .Values.ingress.extraPaths }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          # API requests go to backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "geopulse.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          # Everything else goes to frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "geopulse.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}