{{- $route := .Values.route }}
{{- if $route.enabled }}
{{- $useDefaultGateways := $route.useDefaultGateways | default "" }}
{{- if and $useDefaultGateways (not (or (eq $useDefaultGateways "All") (eq $useDefaultGateways "None"))) }}
{{- fail "route.useDefaultGateways must be either 'All' or 'None'" }}
{{- end }}
{{- if and (empty $route.parentRefs) (ne $useDefaultGateways "All") }}
{{- fail "route.parentRefs must be set when route.enabled=true, unless route.useDefaultGateways is explicitly set to 'All'" }}
{{- end }}
apiVersion: {{ $route.apiVersion | default "gateway.networking.k8s.io/v1" }}
kind: {{ $route.kind | default "HTTPRoute" }}
metadata:
  name: {{ include "geopulse.fullname" . }}
  labels:
    {{- include "geopulse.labels" . | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $route.useDefaultGateways }}
  useDefaultGateways: {{ . | quote }}
  {{- end }}
  {{- with $route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- if $route.httpsRedirect }}
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
    {{- else }}
    {{- if $route.additionalRules }}
    {{- tpl (toYaml $route.additionalRules) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ include "geopulse.fullname" $ }}-frontend
          port: {{ .Values.frontend.service.port | default 80 }}
          weight: 1
      {{- with $route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.matches }}
      matches:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
