{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geopulse.fullname" . }}-mosquitto
  labels:
    {{- include "geopulse.mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mosquitto.service.type }}
  ports:
    - port: {{ .Values.mosquitto.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
      {{- if and (eq .Values.mosquitto.service.type "NodePort") .Values.mosquitto.service.nodePort }}
      nodePort: {{ .Values.mosquitto.service.nodePort }}
      {{- end }}
  selector:
    {{- include "geopulse.mosquitto.selectorLabels" . | nindent 4 }}
{{- end }}