ALTER TABLE users
    ADD COLUMN IF NOT EXISTS custom_map_style_url VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS map_render_mode VARCHAR(32) NOT NULL DEFAULT 'RASTER';

ALTER TABLE shared_link
    ADD COLUMN IF NOT EXISTS custom_map_style_url VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS map_render_mode VARCHAR(32) NOT NULL DEFAULT 'RASTER';
