package org.github.tess1o.geopulse.notifications.model.entity;

public enum NotificationType {
    GEOFENCE_ENTER,
    GEOFENCE_LEAVE,
    TIMELINE_REGENERATION_REQUIRED,
    IMPORT_COMPLETED,
    IMPORT_FAILED,
    EXPORT_COMPLETED,
    EXPORT_FAILED,
    FRIEND_INVITE_RECEIVED,
    FRIEND_INVITE_ACCEPTED,
    WEATHER_QUOTA_REACHED,
    WEATHER_QUOTA_RESTORED,
    GPS_HEALTH_INCIDENT_OPENED,
    GPS_HEALTH_INCIDENT_RESOLVED,
    PRODUCT_RELEASE_AVAILABLE,
    REWIND_READY
}
