export const TIMELINE_PREFERENCES_SCHEMA_VERSION = 'timeline-preferences.v1'

export const TIMELINE_PREFERENCE_LABELS = {
  staypointRadiusMeters: 'Stay Detection Radius',
  staypointMinDurationMinutes: 'Minimum Stay Duration',
  useVelocityAccuracy: 'Enhanced Filtering',
  staypointVelocityThreshold: 'Velocity Threshold',
  staypointMaxAccuracyThreshold: 'GPS Accuracy Threshold',
  staypointMinAccuracyRatio: 'Minimum Accuracy Ratio',
  tripDetectionAlgorithm: 'Trip Detection Algorithm',
  walkingMaxAvgSpeed: 'Walking Maximum Average Speed',
  walkingMaxMaxSpeed: 'Walking Maximum Peak Speed',
  carEnabled: 'Car Detection Enabled',
  carMinAvgSpeed: 'Car Minimum Average Speed',
  carMinMaxSpeed: 'Car Minimum Peak Speed',
  shortDistanceKm: 'Short Trip Distance Threshold',
  bicycleEnabled: 'Bicycle Detection Enabled',
  bicycleMinAvgSpeed: 'Bicycle Minimum Average Speed',
  bicycleMaxAvgSpeed: 'Bicycle Maximum Average Speed',
  bicycleMaxMaxSpeed: 'Bicycle Maximum Peak Speed',
  runningEnabled: 'Running Detection Enabled',
  runningMinAvgSpeed: 'Running Minimum Average Speed',
  runningMaxAvgSpeed: 'Running Maximum Average Speed',
  runningMaxMaxSpeed: 'Running Maximum Peak Speed',
  trainEnabled: 'Train Detection Enabled',
  trainMinAvgSpeed: 'Train Minimum Average Speed',
  trainMaxAvgSpeed: 'Train Maximum Average Speed',
  trainMinMaxSpeed: 'Train Minimum Peak Speed',
  trainMaxMaxSpeed: 'Train Maximum Peak Speed',
  trainMaxSpeedVariance: 'Train Maximum Speed Variance',
  flightEnabled: 'Flight Detection Enabled',
  flightMinAvgSpeed: 'Flight Minimum Average Speed',
  flightMinMaxSpeed: 'Flight Minimum Peak Speed',
  tripArrivalDetectionMinDurationSeconds: 'Arrival Detection Duration',
  tripSustainedStopMinDurationSeconds: 'Sustained Stop Duration',
  tripArrivalMinPoints: 'Minimum Stop Points for Arrival Detection',
  isMergeEnabled: 'Stay Point Merging Enabled',
  mergeMaxDistanceMeters: 'Maximum Merge Distance',
  mergeMaxTimeGapMinutes: 'Maximum Merge Time Gap',
  dataGapThresholdSeconds: 'Data Gap Threshold',
  dataGapMinDurationSeconds: 'Minimum Gap Duration',
  gapStayInferenceEnabled: 'Gap Stay Inference',
  gapStayInferenceMaxGapHours: 'Gap Stay Inference Max Gap Duration',
  gapTripInferenceEnabled: 'Gap Trip Inference',
  gapTripInferenceMinDistanceMeters: 'Gap Trip Inference Minimum Distance',
  gapTripInferenceMinGapHours: 'Gap Trip Inference Minimum Gap Duration',
  gapTripInferenceMaxGapHours: 'Gap Trip Inference Maximum Gap Duration'
}

export const TIMELINE_PREFERENCE_TAB_BY_KEY = {
  staypointRadiusMeters: 'staypoints',
  staypointMinDurationMinutes: 'staypoints',
  useVelocityAccuracy: 'staypoints',
  staypointVelocityThreshold: 'staypoints',
  staypointMaxAccuracyThreshold: 'staypoints',
  staypointMinAccuracyRatio: 'staypoints',

  tripDetectionAlgorithm: 'trips',
  walkingMaxAvgSpeed: 'trips',
  walkingMaxMaxSpeed: 'trips',
  carEnabled: 'trips',
  carMinAvgSpeed: 'trips',
  carMinMaxSpeed: 'trips',
  shortDistanceKm: 'trips',
  bicycleEnabled: 'trips',
  bicycleMinAvgSpeed: 'trips',
  bicycleMaxAvgSpeed: 'trips',
  bicycleMaxMaxSpeed: 'trips',
  runningEnabled: 'trips',
  runningMinAvgSpeed: 'trips',
  runningMaxAvgSpeed: 'trips',
  runningMaxMaxSpeed: 'trips',
  trainEnabled: 'trips',
  trainMinAvgSpeed: 'trips',
  trainMaxAvgSpeed: 'trips',
  trainMinMaxSpeed: 'trips',
  trainMaxMaxSpeed: 'trips',
  trainMaxSpeedVariance: 'trips',
  flightEnabled: 'trips',
  flightMinAvgSpeed: 'trips',
  flightMinMaxSpeed: 'trips',
  tripArrivalDetectionMinDurationSeconds: 'trips',
  tripSustainedStopMinDurationSeconds: 'trips',
  tripArrivalMinPoints: 'trips',

  dataGapThresholdSeconds: 'gpsgaps',
  dataGapMinDurationSeconds: 'gpsgaps',
  gapStayInferenceEnabled: 'gpsgaps',
  gapStayInferenceMaxGapHours: 'gpsgaps',
  gapTripInferenceEnabled: 'gpsgaps',
  gapTripInferenceMinDistanceMeters: 'gpsgaps',
  gapTripInferenceMinGapHours: 'gpsgaps',
  gapTripInferenceMaxGapHours: 'gpsgaps',

  isMergeEnabled: 'merging',
  mergeMaxDistanceMeters: 'merging',
  mergeMaxTimeGapMinutes: 'merging'
}

export const TIMELINE_PREFERENCE_VISIBILITY_HINTS = {
  staypointVelocityThreshold: 'Enable "Enhanced Filtering" to edit this setting.',
  staypointMaxAccuracyThreshold: 'Enable "Enhanced Filtering" to edit this setting.',
  staypointMinAccuracyRatio: 'Enable "Enhanced Filtering" to edit this setting.',
  gapStayInferenceMaxGapHours: 'Enable "Gap Stay Inference" to edit this setting.',
  gapTripInferenceMinDistanceMeters: 'Enable "Gap Trip Inference" to edit this setting.',
  gapTripInferenceMinGapHours: 'Enable "Gap Trip Inference" to edit this setting.',
  gapTripInferenceMaxGapHours: 'Enable "Gap Trip Inference" to edit this setting.'
}
