package org.github.tess1o.geopulse.shared.graalvm;

import io.quarkus.runtime.annotations.RegisterForReflection;

@RegisterForReflection(targets = {
        org.eclipse.paho.client.mqttv3.logging.JSR47Logger.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModuleFactory.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketFrame.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketNetworkModule.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketNetworkModuleFactory.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.HandshakeFailedException.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.class,
        org.eclipse.paho.client.mqttv3.internal.websocket.Base64.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttUnsubscribe.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttPubRel.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttDisconnect.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttReceivedMessage.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttPingReq.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttPubRec.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttAck.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttPingResp.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttConnect.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MultiByteArrayInputStream.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttConnack.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttOutputStream.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttPubAck.class,
        org.eclipse.paho.client.mqttv3.internal.wire.CountingInputStream.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttSuback.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttPubComp.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttPersistableWireMessage.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttUnsubAck.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MqttSubscribe.class,
        org.eclipse.paho.client.mqttv3.internal.wire.MultiByteInteger.class,
        org.eclipse.paho.client.mqttv3.internal.security.SimpleBase64Encoder.class,
        org.eclipse.paho.client.mqttv3.internal.security.SSLSocketFactoryFactory.class,
        org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.class,
        org.eclipse.paho.client.mqttv3.internal.IDisconnectedBufferCallback.class,
        org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.class,
        org.eclipse.paho.client.mqttv3.internal.DestinationProvider.class,
        org.eclipse.paho.client.mqttv3.internal.SSLNetworkModuleFactory.class,
        org.eclipse.paho.client.mqttv3.internal.IDiscardedBufferMessageCallback.class,
        org.eclipse.paho.client.mqttv3.internal.ClientState.class,
        org.eclipse.paho.client.mqttv3.internal.CommsTokenStore.class,
        org.eclipse.paho.client.mqttv3.internal.NetworkModuleService.class,
        org.eclipse.paho.client.mqttv3.internal.MqttPersistentData.class,
        org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.class,
        org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.class,
        org.eclipse.paho.client.mqttv3.internal.CommsSender.class,
        org.eclipse.paho.client.mqttv3.internal.TCPNetworkModuleFactory.class,
        org.eclipse.paho.client.mqttv3.internal.Token.class,
        org.eclipse.paho.client.mqttv3.internal.NetworkModule.class,
        org.eclipse.paho.client.mqttv3.internal.HighResolutionTimer.class,
        org.eclipse.paho.client.mqttv3.internal.MessageCatalog.class,
        org.eclipse.paho.client.mqttv3.internal.ClientComms.class,
        org.eclipse.paho.client.mqttv3.internal.FileLock.class,
        org.eclipse.paho.client.mqttv3.internal.CommsReceiver.class,
        org.eclipse.paho.client.mqttv3.internal.CommsCallback.class,
        org.eclipse.paho.client.mqttv3.internal.DisconnectedMessageBuffer.class,
        org.eclipse.paho.client.mqttv3.internal.ResourceBundleCatalog.class,
        org.eclipse.paho.client.mqttv3.internal.SystemHighResolutionTimer.class
})
public class MqttNativeConfig {
}
