package org.github.tess1o.geopulse.shared.api;

import jakarta.ws.rs.core.Response;

import java.net.URI;

public enum ApiErrorCode {
    AI_API_KEY_REQUIRED(409),
    AI_CONNECTION_FAILED(400),
    AI_CONTEXT_TOO_LARGE(413),
    AI_DISABLED(409),
    AI_PROVIDER_AUTHENTICATION_FAILED(422),
    AI_RATE_LIMITED(429),
    API_TOKEN_INVALID(400),
    ADMIN_SELF_DISABLE_FORBIDDEN(400),
    ADMIN_SELF_DELETE_FORBIDDEN(400),
    ADMIN_USER_NOT_FOUND(404),
    ADMIN_USER_UPDATE_INVALID(400),
    BOAT_SETUP_JOB_NOT_FOUND(404),
    BACKUP_FAILED(500),
    BACKUP_OPERATION_CONFLICT(409),
    COVERAGE_DISABLED(403),
    COVERAGE_ENABLED_REQUIRED(400),
    COVERAGE_RECALCULATION_CONFLICT(409),
    CITY_NOT_FOUND(404),
    COUNTRY_NOT_FOUND(404),
    APPRISE_TEST_FAILED(502),
    EXPORT_EXPIRED(410),
    EXPORT_FILE_MISSING(410),
    EXPORT_NOT_FOUND(404),
    EXPORT_NOT_READY(409),
    FAVORITE_ACCESS_DENIED(403),
    FAVORITE_NOT_FOUND(404),
    FAVORITES_BULK_CREATE_FAILED(400),
    FAVORITES_BULK_UPDATE_FAILED(400),
    FRIEND_INVITATION_ACCESS_DENIED(403),
    FRIEND_INVITATION_NOT_FOUND(404),
    FRIEND_INVITATION_RECIPIENT_NOT_FOUND(404),
    FRIEND_INVITATION_WRONG_STATUS(409),
    FRIEND_LOCATION_ACCESS_DENIED(403),
    FRIEND_LOCATION_NOT_FOUND(404),
    FRIEND_RELATIONSHIP_NOT_FOUND(404),
    GPS_POINT_ACCESS_DENIED(403),
    GPS_POINT_DUPLICATE(409),
    GPS_POINT_NOT_FOUND(404),
    GPS_SOURCE_NOT_FOUND(404),
    GEOCODING_ACCESS_DENIED(403),
    GEOCODING_RESULT_NOT_FOUND(404),
    IMMICH_PHOTO_NOT_FOUND(404),
    INVALID_BOUNDING_BOX(400),
    INVALID_BACKUP_REQUEST(400),
    INVALID_AI_REQUEST(400),
    INVALID_CREDENTIALS(401),
    INVALID_DATE_RANGE(400),
    INVALID_DEBUG_EXPORT_REQUEST(400),
    INVALID_DIGEST_MONTH(400),
    INVALID_DIGEST_VIEW_MODE(400),
    INVALID_DIGEST_YEAR(400),
    INVALID_EXPORT_REQUEST(400),
    INVALID_FAVORITE(400),
    INVALID_FRIEND_ID(400),
    INVALID_FRIEND_INVITATION(400),
    INVALID_FRIEND_TRAIL_RANGE(400),
    INVALID_GEOFENCE_QUERY(400),
    INVALID_GEOFENCE_RULE(400),
    INVALID_GEOCODING_REQUEST(400),
    INVALID_CUSTOM_GEOCODING_PROVIDER(400),
    INVALID_GPS_SOURCE(400),
    INVALID_GPS_QUERY(400),
    INVALID_IMMICH_CONFIG(400),
    INVALID_IMMICH_SEARCH(400),
    INVALID_HEATMAP_LAYER(400),
    INVALID_HEATMAP_RANGE(400),
    INVALID_LIMIT(400),
    INVALID_LOCATION_SEARCH(400),
    INVALID_LOCATION_LOOKUP(400),
    INVALID_MAP_MATCHING_REQUEST(400),
    INVALID_PAGE(400),
    INVALID_STATISTICS_RANGE(400),
    INVALID_PLACE_REQUEST(400),
    INVALID_MEMOS_CONFIG(400),
    INVALID_NOTE_RANGE(400),
    INVALID_NOTE_REQUEST(400),
    INVALID_NOTIFICATION_PREFERENCES(400),
    INVALID_NOTIFICATION_TEMPLATE(400),
    INVALID_TIMELINE_LABEL_DELETE_MODE(400),
    INVALID_TIMELINE_LABEL_RANGE(400),
    INVALID_TIMELINE_LABEL(400),
    INVALID_RELEASE_ANNOUNCEMENT(400),
    INVALID_RECONCILIATION_JOB_ID(400),
    INVALID_TELEMETRY_MAPPING(400),
    INVALID_TIMELINE_JOB_ID(400),
    INVALID_TIMELINE_REQUEST(400),
    INVALID_TRIP_PLAN_ITEM(400),
    INVALID_TRIP_RECONSTRUCTION(400),
    INVALID_TRIP_REQUEST(400),
    INVALID_TRIP_SEARCH(400),
    INVALID_USER_ID(400),
    INVALID_AVATAR(400),
    INVALID_PASSWORD(400),
    INVALID_TIMELINE_PREFERENCES(400),
    INVALID_ADMIN_SETTINGS(400),
    INVALID_ADMIN_SETTINGS_BACKUP(400),
    MAP_MATCHING_DISABLED(400),
    MAP_MATCHING_BACKFILL_DISABLED(400),
    MAP_MATCHING_PROVIDER_NOT_CONFIGURED(400),
    MAP_MATCHING_MODE_INVALID(400),
    INVALID_DEMO_PERSONA(400),
    INVALID_INVITATION(400),
    INVALID_IMPORT_FORMAT(400),
    INVALID_IMPORT_FILE(400),
    INVALID_IMPORT_FILE_TYPE(400),
    INVALID_IMPORT_OPTIONS(400),
    INVALID_IMPORT_REQUEST(400),
    INVALID_IMPORT_CHUNK(400),
    INVALID_IMPORT_CHUNK_INDEX(400),
    INVALID_REFRESH_TOKEN(400),
    INVITATION_NOT_FOUND(404),
    IMPORT_JOB_NOT_FOUND(404),
    IMPORT_ACTIVE_JOB_CONFLICT(409),
    IMPORT_ACTIVE_UPLOAD_CONFLICT(409),
    IMPORT_UPLOAD_NOT_FOUND(404),
    IMPORT_UPLOAD_EXPIRED(410),
    IMPORT_UPLOAD_INVALID_STATE(409),
    IMPORT_UPLOAD_INCOMPLETE(409),
    IMPORT_FILE_TOO_LARGE(413),
    IMPORT_CHUNK_SAVE_FAILED(500),
    IMPORT_ASSEMBLY_FAILED(500),
    IMPORT_FAILED(500),
    INVALID_DEBUG_IMPORT(400),
    DEBUG_IMPORT_FAILED(500),
    MOBILE_SESSION_CODE_INVALID(410),
    NO_FAVORITES_PROVIDED(400),
    GEOFENCE_EVENT_NOT_FOUND(404),
    GEOFENCE_RULE_NOT_FOUND(404),
    NOTIFICATION_NOT_FOUND(404),
    NOTIFICATION_TEMPLATE_NOT_FOUND(404),
    NORMALIZATION_RULE_ACCESS_DENIED(403),
    NORMALIZATION_RULE_NOT_FOUND(404),
    NOTE_NOT_FOUND(404),
    OIDC_ACCOUNT_LINKING_FAILED(400),
    OIDC_ACCOUNT_LINKING_REQUIRED(409),
    OIDC_AUTHENTICATION_FAILED(500),
    OIDC_LOGIN_DISABLED(403),
    OIDC_PROVIDER_INVALID(400),
    OIDC_PROVIDER_NOT_FOUND(404),
    OIDC_PROVIDER_CONFLICT(409),
    OIDC_PROVIDER_ENVIRONMENT_ONLY(400),
    OIDC_PROVIDER_ENVIRONMENT_MISSING(400),
    OIDC_PROVIDER_CONNECTION_FAILED(502),
    OIDC_REGISTRATION_DISABLED(403),
    PASSWORD_LOGIN_DISABLED(403),
    DEMO_LOGIN_UNAVAILABLE(404),
    DEMO_PERSONA_NOT_FOUND(404),
    REFRESH_TOKEN_REQUIRED(401),
    PLACE_NOT_FOUND(404),
    PLACE_RENAME_NOT_ALLOWED(409),
    TIMELINE_LABEL_NOT_FOUND(404),
    LOCATION_VISITS_NOT_FOUND(404),
    RECONCILIATION_ALREADY_ACTIVE(409),
    RECONCILIATION_JOB_ACCESS_DENIED(403),
    RECONCILIATION_JOB_NOT_FOUND(404),
    RESTORE_OPERATION_CONFLICT(409),
    RESTORE_PREPARATION_FAILED(500),
    RESTORE_IN_PROGRESS(503),
    SHARED_LINK_ACCESS_DENIED(403),
    SHARED_LINK_LIMIT_EXCEEDED(429),
    SHARED_LINK_NOT_FOUND(404),
    SHARED_LINK_PASSWORD_INVALID(403),
    SHARED_LINK_TOKEN_REQUIRED(401),
    SHARED_LOCATION_NOT_FOUND(404),
    INVALID_SHARE_LINK(400),
    INVALID_SHARED_TIME_RANGE(400),
    STAY_NOT_FOUND(404),
    DATA_GAP_NOT_FOUND(404),
    DATA_GAP_OVERRIDE_NOT_FOUND(404),
    TIMELINE_JOB_ACCESS_DENIED(403),
    TIMELINE_JOB_ALREADY_ACTIVE(409),
    TIMELINE_JOB_NOT_FOUND(404),
    TIMELINE_REGENERATION_CAMPAIGN_INVALID(400),
    TIMELINE_REGENERATION_CAMPAIGN_NOT_FOUND(404),
    TRIP_NOT_FOUND(404),
    TRIP_PLAN_ITEM_NOT_FOUND(404),
    TRIP_SPLIT_OVERRIDE_NOT_FOUND(404),
    UNSUPPORTED_COVERAGE_GRID(400),
    USER_REGISTRATION_CONFLICT(409),
    WEATHER_BACKFILL_INVALID(400),
    WEATHER_TARGET_NOT_FOUND(404),

    VALIDATION_FAILED(400),
    BAD_REQUEST(400),
    AUTHENTICATION_REQUIRED(401),
    ACCESS_DENIED(403),
    NOT_FOUND(404),
    METHOD_NOT_ALLOWED(405),
    CONFLICT(409),
    GONE(410),
    PAYLOAD_TOO_LARGE(413),
    UNSUPPORTED_MEDIA_TYPE(415),
    UNPROCESSABLE_ENTITY(422),
    RATE_LIMIT_EXCEEDED(429),
    INTERNAL_ERROR(500),
    BAD_GATEWAY(502),
    SERVICE_UNAVAILABLE(503),
    GATEWAY_TIMEOUT(504);

    private final int statusCode;

    ApiErrorCode(int statusCode) {
        this.statusCode = statusCode;
    }

    public int statusCode() {
        return statusCode;
    }

    public String title() {
        Response.Status status = Response.Status.fromStatusCode(statusCode);
        return status == null ? "HTTP Error" : status.getReasonPhrase();
    }

    public URI typeUri() {
        return URI.create("urn:geopulse:error:" + name());
    }

    public static ApiErrorCode forStatus(int statusCode) {
        return switch (statusCode) {
            case 400 -> BAD_REQUEST;
            case 401 -> AUTHENTICATION_REQUIRED;
            case 403 -> ACCESS_DENIED;
            case 404 -> NOT_FOUND;
            case 405 -> METHOD_NOT_ALLOWED;
            case 409 -> CONFLICT;
            case 410 -> GONE;
            case 413 -> PAYLOAD_TOO_LARGE;
            case 415 -> UNSUPPORTED_MEDIA_TYPE;
            case 422 -> UNPROCESSABLE_ENTITY;
            case 429 -> RATE_LIMIT_EXCEEDED;
            case 502 -> BAD_GATEWAY;
            case 503 -> SERVICE_UNAVAILABLE;
            case 504 -> GATEWAY_TIMEOUT;
            default -> statusCode >= 500 ? INTERNAL_ERROR : BAD_REQUEST;
        };
    }
}
